# Dokapi_url is deprecated. Please use folio.client.okapiUrl instead
Dokapi_url: http://localhost:9130
# okapi_url is deprecated. Please use folio.client.okapiUrl instead
okapi_url: ${Dokapi_url}
Dsecure_store_props: src/main/resources/ephemeral.properties
secure_store_props: ${Dsecure_store_props}
Dsecure_store: Ephemeral
secure_store: ${Dsecure_store}
Dstaging_director_tenants: stagingDirector_tenants
staging_director_tenants: ${Dstaging_director_tenants}
Dstaging_director_client: stagingDirector
staging_director_client: ${Dstaging_director_client}
api_key_sources: PARAM,HEADER
spring:
  application:
    name: edge-dematic
  jackson:
    default-property-inclusion: non_null
  liquibase:
    enabled: false
  flyway:
    enabled: false
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: health,info,loggers
  endpoint:
    loggers:
      enabled: true
feign:
  client:
    config:
      default:
        loggerLevel: full
folio:
  system-user:
    username: ${SYSTEM_USER_NAME:system-user}
    password: ${SYSTEM_USER_PASSWORD}
  environment: ${ENV:folio}
  client:
    okapiUrl: http://localhost:9130
    tls:
      enabled: false
#      trustStorePath: ~/test/test.truststore.bcfks
#      trustStorePassword: "SecretPassword"
#      trustStoreType: BCFKS

logging:
  level:
    org:
      springframework:
        cache: OFF

server.port: 8081
folio.tenant.validation.enabled: false

# heartbeat timeframe for the primary channel (seconds)
primary.channel.heartbeat.timeframe: 30

# configurations update timeframe (millis)
configurations.update.timeframe: 3600000
