Dokapi_url: http://localhost:9130
okapi_url: ${Dokapi_url}
Dsecure_store_props: src/main/resources/ephemeral.properties
secure_store_props: ${Dsecure_store_props}
Dsecure_store: Ephemeral
secure_store: ${Dsecure_store}
api_key_sources: PARAM,HEADER
spring:
  application:
    name: edge-dematic
  jackson:
    default-property-inclusion: non_null
  liquibase:
    enabled: false
  flyway:
    enabled: false
management:
  endpoints:
    web:
      base-path: /admin
feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    org:
      springframework:
        cache: OFF

server.port: 8081
folio.tenant.validation.enabled: false

# heartbeat timeframe for the primary channel (seconds)
primary.channel.heartbeat.timeframe: 30

# configurations update timeframe (millis)
configurations.update.timeframe: 3600000
